### ISSUE TITLE
component/MovieCruiser/index.js line no:7 super(props) need to be called instead of super()

### ISSUE THREAD

**Issue by raghuprathap** [hellopramith/movieAppRedux#1]
Please refer the documentation -  

The constructor for a React component is called before it is mounted. When implementing the constructor for a React.Component subclass, you should call super(props) before any other statement. Otherwise, this.props will be undefined in the constructor, which can lead to bugs.

https://reactjs.org/docs/react-component.html#constructor

**Comment by pramithprakash** [comment]
Updated the code as per comments

**Comment by Fawke** [comment]
@pramithprakash thanks for the update, you can now close this issue. We are marking this assignment as completed.
